# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: "no"
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
    volumes:
      - ./database:/var/lib/mysql

  adminer:
    image: adminer
    restart: "no"
    ports:
      - 8080:8080

volumes:
  database: