# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: "no"
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080